// 🤖 AUTOGENERATED FILE - DO NOT EDIT MANUALLY!
// This file is automatically generated by the 'generate-widget-registry.js' script.
// It contains the logic registry for all widgets.
import { WidgetType } from './autogen.types';
import { BoraWidget } from './bora-widget';
import { IBaseWidget } from '@/types/widgets';
import { IconWidget } from './../icon-widget/widget';
import { TextWidget } from './../text-widget/widget';
import { ValueWidget } from './../value-widget/widget';

export const widgetLogicRegistry: Record<WidgetType, BoraWidget<IBaseWidget>>  = {
  "Icon": new IconWidget(),
  "Text": new TextWidget(),
  "Value": new ValueWidget(),
};
