// 🤖 AUTOGENERATED FILE (SERVER) - DO NOT EDIT MANUALLY!
// Contains only types + metadata (no class imports).

import { ITextWidget, IValueWidget } from '@/types/widgets';

export type IWidget = ITextWidget | IValueWidget;
export type WidgetType = "Text" | "Value";
export const widgetTypes = ["Text", "Value"] as const;
