// 🤖 AUTOGENERATED FILE - DO NOT EDIT MANUALLY!

import { IconWidget } from '../icon-widget';
import { TextWidget } from '../text-widget';
import { ValueWidget } from '../value-widget';
import { IIconWidget, ITextWidget, IValueWidget } from '@/types/widgets';

/** A union type representing the data structure of every possible widget. */
export type IWidget = IIconWidget | ITextWidget | IValueWidget;

/** A type containing all possible widget type strings (e.g. "TEXT" | "IMAGE"). */
export type WidgetType = keyof typeof widgetRegistry;

// Singleton instances for each widget handler
const iconwidgetInstance = new IconWidget();
const textwidgetInstance = new TextWidget();
const valuewidgetInstance = new ValueWidget();

/** * A central registry that maps each widget type string to the corresponding 
 * handler instance.
 */
export const widgetRegistry = {
  "Icon": iconwidgetInstance,
  "Text": textwidgetInstance,
  "Value": valuewidgetInstance,
} as const;
