"use client";

// 🤖 AUTOGENERATED FILE (CLIENT) - DO NOT EDIT MANUALLY!
// Provides widgetRegistry with instantiated widget handler classes.

import { IconWidget } from '../icon-widget';
import { TextWidget } from '../text-widget';
import { ValueWidget } from '../value-widget';

// Singleton instances
const IconWidgetInstance = new IconWidget();
const TextWidgetInstance = new TextWidget();
const ValueWidgetInstance = new ValueWidget();

// Registry mapping type -> handler instance
export const widgetRegistry = {
  "Icon": IconWidgetInstance,
  "Text": TextWidgetInstance,
  "Value": ValueWidgetInstance,
} as const;
