"use client";

// 🤖 AUTOGENERATED FILE (CLIENT) - DO NOT EDIT MANUALLY!
// This file is automatically generated by the 'generate-widget-registry.js' script.
// It contains the UI registry for all widgets.
import { FC } from "react";
import { WidgetType, IWidget } from './autogen.types';
import { IconWidgetComponent, IconWidgetForm } from './../icon-widget/components';
import { TextWidgetComponent, TextWidgetForm } from './../text-widget/components';
import { ValueWidgetComponent, ValueWidgetForm } from './../value-widget/components';

type WidgetUIRegistry = Record<WidgetType, {
  component: FC<any>;
  form: FC<any>;
}>;

export const widgetUIRegistry: WidgetUIRegistry = {
  "Icon": {
    component: IconWidgetComponent,
    form: IconWidgetForm,
  },
  "Text": {
    component: TextWidgetComponent,
    form: TextWidgetForm,
  },
  "Value": {
    component: ValueWidgetComponent,
    form: ValueWidgetForm,
  },
} as const;
