// 🤖 AUTOGENERATED FILE (SERVER) - DO NOT EDIT MANUALLY!
// Contains only types + metadata (no class imports).

import { IIconWidget, ITextWidget, IValueWidget } from '@/types/widgets';

export type IWidget = IIconWidget | ITextWidget | IValueWidget;
export type WidgetType = "Icon" | "Text" | "Value";
export const widgetTypes = ["Icon", "Text", "Value"] as const;
